Revolve improvements
ci-group/revolve pull request #32
Opened 2018-12-24 16:27 UTC by milanjelisavcic

This batch of improvements contain:
- [x] Enable configuration options to users
- [x] Create brain selector

2019-01-02 12:25 UTC, portaloffreedom commented on revolve.py
> -        manager_args=['-u', settings.manager],
`-u` option is important or you don't have output from the manager

2019-01-15 12:31 UTC, portaloffreedom requested changes

2019-01-15 12:31 UTC, portaloffreedom commented on cpprevolve/revolve/gazebo/Types.h
`#include <memory>`

2019-01-15 12:31 UTC, portaloffreedom commented on cpprevolve/revolve/gazebo/brains/Brain.h
> -* Description: Specifies a utility `Brain` base class. If your brain doesn't
fix documentation

2019-01-15 12:31 UTC, portaloffreedom commented on cpprevolve/revolve/gazebo/brains/NeuralNetwork.cpp
> -      throw std::runtime_error("Robot brain error");
brainsssssszz

2019-01-15 12:31 UTC, portaloffreedom commented on cpprevolve/revolve/gazebo/brains/NeuralNetwork.cpp
> -    outPos++;
`++outputIndex`

2019-01-15 12:31 UTC, portaloffreedom commented on cpprevolve/revolve/gazebo/plugin/RobotController.cpp
> +  }
else error

2019-01-15 12:31 UTC, portaloffreedom commented on tools/compile_python
>  #!/bin/sh
rename file compile_python.sh

2019-01-15 15:43 UTC, milanjelisavcic commented on cpprevolve/revolve/gazebo/Types.h
Added in #292cd7a commit.

2019-01-15 15:50 UTC, milanjelisavcic commented on cpprevolve/revolve/gazebo/brains/Brain.h
> -* Description: Specifies a utility `Brain` base class. If your brain doesn't
Fixed in daebd2d

2019-01-15 15:50 UTC, zenfiric commented on cpprevolve/revolve/gazebo/brains/NeuralNetwork.cpp
> -      throw std::runtime_error("Robot brain error");
Fixed in daebd2d

2019-01-15 16:02 UTC, zenfiric commented on cpprevolve/revolve/gazebo/plugin/RobotController.cpp
> +  }
Fixed in 05471c4

2019-01-15 16:02 UTC, milanjelisavcic commented on cpprevolve/revolve/gazebo/brains/NeuralNetwork.cpp
> -    outPos++;
Fix in 048524f

2019-01-15 16:06 UTC, milanjelisavcic commented on tools/compile_python
>  #!/bin/sh
Fixed in 53f9fef

2019-01-16 10:34 UTC, portaloffreedom approved these changes

2019-01-16 10:34 UTC, merged